services:
  - type: web
    name: decimal-rate
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NEXT_PUBLIC_DECIMAL_API_URL
        sync: false
      - key: CRON_SECRET_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 